### PR TITLE
primus_vk - change version "master", last commit, to "1.5"

### PR DESCRIPTION
**Pull request by ryuuzaki42**
Hello,

Changed the version of primus_vk, version "master", last commit, to "1.5".
A realease version is somethins more secure and not give the warning

"WARNING: checksum failed: primus_vk/primus_vk-master.tar.gz"

Or updated the md5sum, #55 , choose the better : ).

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
Whoops, I merged the other one on accident, can you rebase and push this back up?

**Comment by ryanpcmcquen** [comment]
@ryuuzaki42, this is the one I wanted actually, can you push it back up (rebased)?

**Comment by ryuuzaki42** [comment]
Hello @ryanpcmcquen , in a new pull request or works in this one?

**Comment by ryanpcmcquen** [comment]
This is great, thanks!

**Pull request merged**
