### PR TITLE
nvidia version update + bbswitch patch

### PR DESCRIPTION
**Pull request by nrj5k**
This should cover the bbswitch patch and the nvidia version bump so that things work well for kernel 5.10.1

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
Does upstream have a new version?

**Comment by nrj5k** [comment]
Kernel version? Yes. Pat released it yesterday

Dec 20, 2020 02:39:51 Ryan McQuen <notifications@github.com>:

**Comment by ryanpcmcquen** [comment]
I meant the bbswitch project. Should try to get it merged there.

**Comment by nrj5k** [comment]
Oh someone has already pushed this patch. I got it from the issues there but it hasn't been merged to a release.

Dec 20, 2020 13:26:16 Ryan McQuen <notifications@github.com>:

**Pull request merged**
