### PR TITLE
Change driver version to 410.73

### PR DESCRIPTION
**Pull request by KhazAkar**
Edited files and edited SlackBuild to be able to package nvidia-bumblebee.

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
Thank you!

**Comment by KhazAkar** [comment]
No problem, Please test if it works properly for you. My first time with Slackware package building etc :)

**Comment by KhazAkar** [comment]
It builds, but libGL keeps segfaulting like this:
```
[  537.077052] glxinfo[2348]: segfault at 0 ip 00007efd1d41a513 sp 00007ffe33e10820 error 4 in libGL.so.1[7efd1d408000+19000]
[  537.077057] Code: e8 e9 0f ff ff ff 90 41 55 41 54 41 89 cc 55 53 48 89 d3 48 83 ec 28 e8 db e1 fe ff 45 89 e0 48 89 d9 ba 14 80 00 00 48 89 c5 <48> 8b 30 48 8b 3d ab be 01 00 ff 15 cd be 01 00 4c 8b 6d 00 48 89
```
And missing GLX when trying to run optirun -vvv glxinfo or primusrun glxinfo. From /var/log/Xorg.8.log:
```
[  1023.019] (II) LoadModule: "glx"
[  1023.020] (II) Loading /usr/lib64/nvidia-bumblebee/xorg/modules/extensions/libglx.so
[  1023.022] (EE) LoadModule: Module glx does not have a glxModuleData data object.
[  1023.022] (EE) Failed to load module "glx" (invalid module, 0)
```

**Comment by ryanpcmcquen** [comment]
Hmmmm ... any ideas @Jheengut or @yukiisbored?

**Pull request merged**
