### PR TITLE
Patch for libglvnd + download.sh

### PR DESCRIPTION
**Pull request by nrj5k**
This fixes the install script for nvidia-bumblebee with a little help from @Francexi and also fixes the download.sh script as mentioned by @lazyfox77 from an earlier issue.

I have not tested it thoroughly but things seem to work, feedback highly appreciated.

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
Thank you for this! Will you resolve the merge conflicts? @WhiteWolf1776, please give @nrj5k write access.

**Comment by nrj5k** [comment]
Sure, I dunno why there would be real conflicts but yeah if I have access then I'll take care of it.

**Comment by ryanpcmcquen** [comment]
@nrj5k, try:

```
git rebase -i master
```

**Comment by nrj5k** [comment]
I think it should be fine now.

**Comment by ryanpcmcquen** [comment]
Thank you @nrj5k!

**Comment by nrj5k** [comment]
Welcome!

**Pull request merged**
